In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [7]:
df_train = pd.read_csv("new_train.data", names=['C1', 'S1', 'C2', 'S2', 'C3', 'S3', 'C4', 'S4', 'C5', 'S5', 'CLASS'])
df_test = pd.read_csv("poker-hand-testing-short.data", names=['C1', 'S1', 'C2', 'S2', 'C3', 'S3', 'C4', 'S4', 'C5', 'S5', 'CLASS'])
df_train

      C1  S1  C2  S2  C3  S3  C4  S4  C5  S5  CLASS
0      2   6   2   1   4  13   2   4   4   9      0
1      1  10   4   6   1   2   1   1   3   8      0
2      2  13   2   1   4   4   1   5   2  11      0
3      1   3   4   7   1   5   2   4   4  13      0
4      3   8   3  12   2   7   2   6   1   2      0
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
3913   3   2   2   5   1   2   2   6   3   5      2
3914   3   4   3   8   4   3   3   3   1   3      3
3915   3   4   1   4   2   4   2   6   3   6      6
3916   4   1   2   1   1   3   2   6   3   1      3
3917   4  12   3  11   4   4   3  12   2  12      3

[3918 rows x 11 columns]

In [9]:
#Get data for training and testing
shuffled_train = df_train.sample(frac=1)
shuffled_test = df_test.sample(frac=1)
train_x, train_y, test_x, test_y = shuffled_train.iloc[:, :-2], shuffled_train.iloc[:, -1], shuffled_test.iloc[:, :-2], shuffled_test.iloc[:, -1]
# print(train_x.shape, train_y.shape, test_x.shape, test_y.shape)
print(type(shuffled_train))

<class 'pandas.core.frame.DataFrame'>

In [10]:
#Make random forest 
clf = RandomForestClassifier(random_state=0)
clf.fit(train_x, train_y)

prediction = clf.predict(test_x)
print(prediction)
# print(test_y)
# clf.score(test_y, prediction)

[0 2 0 ... 0 2 2]

In [17]:
#Calculate the accuracy of the prediction
length = len(shuffled_test)
sum_poker = 0
for index in range(length):
    sum_poker = sum_poker + abs(prediction[index] - test_y[index])
accuracy = sum_poker / length
print(length)
print(accuracy)

2500
0.9668

In [21]:
print(classification_report(prediction, test_y))
print(confusion_matrix(prediction, test_y))

              precision    recall  f1-score   support

           0       0.43      0.61      0.50       903
           1       0.26      0.42      0.32       658
           2       0.55      0.07      0.13       876
           3       0.13      0.09      0.11        57
           4       0.00      0.00      0.00         3
           5       0.33      0.50      0.40         2
           6       0.00      0.00      0.00         1

    accuracy                           0.36      2500
   macro avg       0.24      0.24      0.21      2500
weighted avg       0.42      0.36      0.31      2500

[[547 334  17   3   0   1   1]
 [340 276  29   9   2   1   1]
 [358 430  62  21   3   0   2]
 [ 19  27   5   5   1   0   0]
 [  2   1   0   0   0   0   0]
 [  0   1   0   0   0   1   0]
 [  1   0   0   0   0   0   0]]